# Site settings
title:       Recursive Thoughts!
#email:       alaa.qutaish@gmail.com
author:      Alaa Qutaish
description: "tech and personal thoughts"
baseurl:     ""
url:         "http://alaa.github.io"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:             false
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: alaa

# Social icons
github_username: alaa
bitbucket_username:
stackoverflow_id:
twitter_username: caspereeko
google_plus_id:
linkedin_username: alaaq
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
